spring:
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: true
  messages:
      basename: language/messages
      cache-seconds: 3600
  datasource:
    master:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://bdm256204263.my3w.com:3306/bdm256204263_db?serverTimezone=GMT&characterEncoding=utf8
      username: bdm256204263
      password: mama0927
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    open-in-view: true
    show-sql: true
    database: mysql
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL57InnoDBDialect
      hibernate.format_sql: true
      hibernate.ejb.interceptor: com.khcm.user.dao.interceptor.TreeInterceptor
      javax.persistence.validation.mode: none
  thymeleaf:
    cache: false
    mode: LEGACYHTML5

shiro:
  cipherKey: fPimdozRt+SSSbZS8/HARA==
#  cas:
#    serviceUrl: http://localhost:${server.port}${server.context-path}
#    callbackUrl: http://localhost:${server.port}${server.context-path}/callback
#    preffixUrl: https://sso.sdkhcm.com/xueyuan-cas
#    loginUrl: https://sso.sdkhcm.com/xueyuan-cas/login
#    logoutUrl: https://sso.sdkhcm.com/xueyuan-cas/logout
#    preffixUrl: https://sso.xueyuan.com:8443
#    loginUrl: https://sso.xueyuan.com:8443/login
#    logoutUrl: https://sso.xueyuan.com:8443/logout

logging:
  path: log/
  file: user-admin.log

server:
  context-path: /center-user
  port: 8090