spring:
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: true
  messages:
      basename: language/messages
      cache-seconds: 3600
  datasource:
    master:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/bdm256204263_db?serverTimezone=GMT&characterEncoding=utf8
      username: root
      password: mama0927
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    open-in-view: true
    show-sql: true
    database: mysql
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL57InnoDBDialect
      hibernate.format_sql: true
      hibernate.ejb.interceptor: com.khcm.user.dao.interceptor.TreeInterceptor
      javax.persistence.validation.mode: none
  thymeleaf:
    cache: false
    mode: LEGACYHTML5

shiro:
  cipherKey: fPimdozRt+SSSbZS8/HARA==
logging:
  path: log/
  file: user-admin.log

server:
  context-path: /center-user
  port: 8090