spring:
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: true
  messages:
      basename: language/messages
      cache-seconds: 3600
  datasource:
    master:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://58.57.164.135:60330/xueyuan?serverTimezone=GMT
      username: dev
      password: dev@khcm)^#%
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    open-in-view: true
    show-sql: true
    database: mysql
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL57InnoDBDialect
      hibernate.format_sql: true
      hibernate.ejb.interceptor: com.khcm.user.dao.interceptor.TreeInterceptor
      javax.persistence.validation.mode: none
  thymeleaf:
    cache: false
    mode: LEGACYHTML5

  mail:
    host: smtp.163.com
    username: test@163.com
    password: test

shiro:
  cipherKey: fPimdozRt+SSSbZS8/HARA==
  cas:
    preffixUrl: https://sso.sdkhcm.com/xueyuan-cas
    loginUrl: https://sso.sdkhcm.com/xueyuan-cas/login
    logoutUrl: https://sso.sdkhcm.com/xueyuan-cas/logout
    serviceUrl: http://localhost:${server.port}${server.context-path}
    callbackUrl: http://localhost:${server.port}${server.context-path}/callback

sms:
  tencent:
    appId: 1400065802
    appKey: 9bfe5da45e0f262a229223beebff6d2e

logging:
  path: log/
  file: user-admin.log

server:
  context-path: /xueyuan-user
  port: 8090