spring:
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: true
  messages:
      basename: language/messages
      cache-seconds: 3600
  datasource:
    master:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://58.57.164.135:3306/xueyuan?serverTimezone=GMT
      username: dev
      password: dev@khcm)^#%
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    open-in-view: true
    show-sql: true
    database: mysql
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL57InnoDBDialect
      hibernate.format_sql: true
      hibernate.ejb.interceptor: com.khcm.user.dao.interceptor.TreeInterceptor
      javax.persistence.validation.mode: none
  thymeleaf:
    cache: false

shiro:
  cipherKey: fPimdozRt+SSSbZS8/HARA==

logging:
  path: ~/data/log/
  file: user-admin.log

server:
  context-path: /xueyuan-user